planetpeacepeople/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/urls.py
from django.urls import path

from .views import *

app_name = 'web'

urlpatterns = [
    path('', index, name='index'),
    path('category/<slug:slug>/', blog_category, name='blog_category'),
    path('blog/', blog, name='blog'),
    path('blog/<slug:slug>/', blogdetails, name='blogdetails'),
    path('projects/', projects, name='projects'),
    path('projects/<slug:slug>/', projectdetails, name='projectdetails'),
    path('connect/', contact, name='contact'),
]

web/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from tinymce import models as tinymce_models

class BlogCategory(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='blog_category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'blog_category'
        verbose_name_plural = 'blog_categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('web:blog_category', args=[self.slug])

# Create your models here.
class Blog(models.Model):
    category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE, related_name='blog_category', blank=True, null=True)
    title = models.CharField(max_length=200)
    date = models.DateField()
    image = models.ImageField(upload_to='images/')
    description = tinymce_models.HTMLField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)


    def __str__(self):
        return self.title

    def summary(self):
        summary = self.description.split(' ')
        return ' '.join(summary[:20])

    def imageUrl(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
    def absolute_url(self):
        return "/blog/%s/" % self.slug

    def pub_day(self):
        return self.date.strftime('%d')
    
    def pub_month(self):
        return self.date.strftime('%b')

    def pub_date_pretty(self):
        return self.date.strftime('%b %e %Y')

class Projects(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField()
    image = models.ImageField(upload_to='images/')
    description = tinymce_models.HTMLField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)

    def __str__(self):
        return self.title

    def summary(self):
        summary = self.description.split(' ')
        return ' '.join(summary[:20])

    def imageUrl(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
    def absolute_url(self):
        return "/projects/%s/" % self.slug

    def pub_day(self):
        return self.date.strftime('%d')
    
    def pub_month(self):
        return self.date.strftime('%b')

    def pub_date_pretty(self):
        return self.date.strftime('%b %e %Y')

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=200)
    # gender_choices = (
    #     ('male','Male'),
    #     ('female','Female'),
    # )
    # gender = models.CharField(max_length=200, choices=gender_choices)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    message = models.TextField()
    add_date = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.name

    def summary(self):
        return self.message[:157]

web/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Blog, BlogCategory, Projects, Contact
from django.contrib import messages
# Create your views here.
def index(request):
    count = Contact.objects.all().count()
    blogs = Blog.objects.all()[0:3]
    projects = Projects.objects.all()[0:3]
    return render(request, 'index.html', {'blogs':blogs, 'projects':projects, 'count':count})

def blog_category(request, slug):
    category = BlogCategory.objects.all()
    blogs = Blog.objects.filter(category__slug=slug)
    return render(request, 'blog.html', {'blogs':blogs, 'category':category})

def blog(request):
    category = BlogCategory.objects.all()
    blogs = Blog.objects.all()
    return render(request, 'blog.html', {'blogs':blogs, 'category':category})

def blogdetails(request, slug):
    category = BlogCategory.objects.all()
    blogs = Blog.objects.exclude(slug=slug).all()[0:3]
    blog = get_object_or_404(Blog, slug=slug)
    next_blog = Blog.objects.filter(id__gt=blog.id).first()
    prev_blog = Blog.objects.filter(id__lt=blog.id).last()
    context = {
        'blog':blog,
        'blogs':blogs,
        'category':category,
        'next_blog':next_blog,
        'prev_blog':prev_blog
    }
    return render(request, 'blog_details.html', context)

def about(request):
    return render(request, 'about.html')

def whatwedo(request):
    return render(request, 'what-do.html')

def projects(request):
    projects = Projects.objects.all()
    return render(request, 'projects.html', {'projects':projects})

def projectdetails(request, slug):
    projects = Projects.objects.exclude(slug=slug).all()[0:3]
    project = get_object_or_404(Projects, slug=slug)
    return render(request, 'project_details.html', {'project':project, 'projects':projects})

def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        # gender = request.POST['gender']
        city = request.POST['city']
        country = request.POST['country']
        message = request.POST['message']
        contact = Contact.objects.create(
            name=name,
            email=email,
            phone=phone,
            # gender=gender,
            city=city,
            country=country,
            message=message
        )
        contact.save()
        messages.success(request, 'Your message has been sent!')
        print('Message sent!', name, email)
        return redirect('web:contact')
    return render(request, 'contact.html')

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js' %}" lang="zxx">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %} {% endblock title %} Planet Peace & People</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="manifest" href="site.webmanifest">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
  <!-- CSS here -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/progressbar_barfiller.css' %}">
  <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/animated-headline.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'css/slick.css' %}">
  <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block css %} {% endblock %}
</head>

<body>
  <!-- ? Preloader Start -->
  <div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
      <div class="preloader-inner position-relative">
        <div class="preloader-circle"></div>
        <div class="preloader-img pere-text">
          <img src="{% static 'img/logo/loder.png' %}" alt="">
        </div>
      </div>
    </div>
  </div>
  <!-- Preloader Start -->
  <header>
    <!-- Header Start -->
    <div class="header-area">
      <div class="main-header ">
        <div class="header-bottom  header-sticky">
          <div class="container-fluid">
            <div class="row align-items-center">
              <!-- Logo -->
              <div class="col-xl-2 col-lg-2">
                <div class="logo">
                  <a href="{% url 'web:index' %}"><img src="{% static 'img/logo/logo_ppp.png' %}" alt="" width="250px"></a>
                </div>
              </div>
              <div class="col-xl-10 col-lg-10">
                <div class="menu-wrapper  d-flex align-items-center justify-content-end">
                  <!-- Main-menu -->
                  <div class="main-menu d-none d-lg-block">
                    <nav>
                      <ul id="navigation">
                        <li><a href="{% url 'web:index' %}">Home</a></li>
                        <!-- <li><a href="about.html">About</a></li> -->
                        <li><a href="{% url 'web:index' %}">What we Care About</a></li>
                        <li><a href="{% url 'web:index' %}">Actions</a></li>
                        <li><a href="{% url 'web:blog' %}">Blogs</a>
                        </li>
                        <li><a href="{% url 'web:contact' %}">connect</a></li>
                      </ul>
                    </nav>
                  </div>
                  <!-- Header-btn -->
                  <!-- <div class="header-right-btn d-none d-lg-block ml-20">
                    <a href="contact.html" class="btn header-btn">Make a Donation</a>
                  </div> -->
                </div>
              </div>
              <!-- Mobile Menu -->
              <div class="col-12">
                <div class="mobile_menu d-block d-lg-none"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Header End -->
  </header>
  <main>
    {% block content %} {% endblock %}
  </main>
  <footer>
    <div class="footer-wrapper">
      <!-- Footer Start-->
      <div class="footer-area footer-padding">
        <div class="container ">
          <div class="row justify-content-between">
            <div class="col-xl-4 col-lg-3 col-md-8 col-sm-8">
              <div class="single-footer-caption mb-50">
                <div class="single-footer-caption mb-30">
                  <!-- logo -->
                  <div class="footer-logo mb-35">
                    <a href="{% url 'web:index' %}"><img src="{% static 'img/logo/logo_ppp.png' %}" alt="" width="280px"></a>
                  </div>
                  <div class="footer-tittle">
                    <div class="footer-pera">
                      <p>People need to be in peace with planet.</p>
                    </div>
                  </div>
                  <!-- social -->
                  <div class="footer-social">
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-2 col-lg-3 col-md-4 col-sm-4">
              <div class="single-footer-caption mb-50">
                <div class="footer-tittle">
                  <h4>Track</h4>
                  <ul>
                    <li><a href="https://www.footprintcalculator.org/home/en" target="_blank">Footprint Calculator</a></li>
                    <li><a href="#">Air Pollution</a></li>
                    <li><a href="#">Population</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-xl-2 col-lg-2 col-md-4 col-sm-4">
              <div class="single-footer-caption mb-50">
                <div class="footer-tittle">
                  <h4>Other Sites</h4>
                  <ul>
                    <li><a href="https://www.iucn.org/">IUCN</a></li>
                    <li><a href="https://www.iucnredlist.org/">The IUCN Red List</a></li>
                    <li><a href="https://www.worldwildlife.org/">WWF</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-4">
              <div class="single-footer-caption mb-50">
                <div class="footer-tittle">
                  <h4>Connect</h4>
                  <ul>
                    <li><a href="#">connect@planetpeacepeople.org</a></li>
                    <li><a href="#">A-833, Indra Vihar, Talwandi</a></li>
                    <li><a href="#">Kota, Rajasthan, India 324005</a></li>
                    <li class="number"><a href="#">+91-941 417 8884</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- footer-bottom area -->
      <div class="footer-bottom-area">
        <div class="container">
          <div class="footer-border">
            <div class="row d-flex align-items-center">
              <div class="col-xl-12 ">
                <div class="footer-copy-right text-center">
                  <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved <a href=""
                      target="_blank">Planet Peace People .org</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Footer End-->
    </div>
  </footer>
  <!-- Scroll Up -->
  <div id="back-top">
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
  </div>

  <!-- JS here -->

  <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
  <!-- Jquery, Popper, Bootstrap -->
  <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- Jquery Mobile Menu -->
  <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>

  <!-- Jquery Slick , Owl-Carousel Plugins -->
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/slick.min.js' %}"></script>
  <!-- One Page, Animated-HeadLin -->
  <script src="{% static 'js/wow.min.js' %}"></script>
  <script src="{% static 'js/animated.headline.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

  <!-- Date Picker -->
  <script src="{% static 'js/gijgo.min.js' %}"></script>
  <!-- Nice-select, sticky -->
  <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
  <script src="{% static 'js/jquery.sticky.js' %}"></script>
  <!-- Progress -->
  <script src="{% static 'js/jquery.barfiller.js' %}"></script>

  <!-- counter , waypoint,Hover Direction -->
  <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
  <script src="{% static 'js/waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/hover-direction-snake.min.js' %}"></script>

  <!-- contact js -->
  <script src="{% static 'js/contact.js' %}"></script>
  <script src="{% static 'js/jquery.form.js' %}"></script>
  <script src="{% static 'js/jquery.validate.min.js' %}"></script>
  <script src="{% static 'js/mail-script.js' %}"></script>
  <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>

  <!-- Jquery Plugins, main Jquery -->
  <script src="{% static 'js/plugins.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  {% block scripts %} {% endblock %}
</body>

</html>

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if messages %} 
{% for message in messages %}
<div class="alert alert-info text-center">
    {{ message }}
</div>
{% endfor %}
{% endif %}
<!--? Hero Start -->
<div class="slider-area2">
    <div class="slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap hero-cap2 pt-70">
                        <h2>Blogs</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'web:index' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Blogs</a></li> 
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero End -->
<!--? Blog Area Start-->
<section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5 mb-lg-0">
                <div class="blog_left_sidebar">
                    {% for blog in blogs %}
                    <article class="blog_item">
                        <div class="blog_item_img">
                            <img class="card-img rounded-0" src="{{blog.imageUrl}}" alt="">
                            <a href="#" class="blog_item_date">
                                <h3>{{blog.pub_day}}</h3>
                                <p>{{blog.pub_month}}</p>
                            </a>
                        </div>
                        <div class="blog_details">
                            <a class="d-inline-block" href="{% url 'web:blogdetails' blog.slug %}">
                                <h2 class="blog-head" style="color: #2d2d2d;">{{blog.title}}</h2>
                            </a>
                            {{blog.summary|safe}}
                            <ul class="blog-info-link">
                                <li><a href="#"><i class="fa fa-user"></i> {{blog.author.first_name}}</a></li>
                                <li><a href="#"><i class="fa fa-comments"></i> 03 Comments</a></li>
                            </ul>
                        </div>
                    </article>
                    {% endfor %}
                    <nav class="blog-pagination justify-content-center d-flex">
                        <ul class="pagination">
                            <li class="page-item">
                                <a href="#" class="page-link" aria-label="Previous">
                                    <i class="ti-angle-left"></i>
                                </a>
                            </li>
                            <li class="page-item">
                                <a href="#" class="page-link">1</a>
                            </li>
                            <li class="page-item active">
                                <a href="#" class="page-link">2</a>
                            </li>
                            <li class="page-item">
                                <a href="#" class="page-link" aria-label="Next">
                                    <i class="ti-angle-right"></i>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget search_widget">
                        <form action="#">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" placeholder='Search Keyword'
                                    onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = 'Search Keyword'">
                                    <div class="input-group-append">
                                        <button class="btns" type="button"><i class="ti-search"></i></button>
                                    </div>
                                </div>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                            type="submit">Search</button>
                        </form>
                    </aside>
                    <aside class="single_sidebar_widget post_category_widget">
                        <h4 class="widget_title" style="color: #2d2d2d;">Category</h4>
                        <ul class="list cat-list">
                            {% for c in category %}
                            <li>
                                <a href="#" class="d-flex">
                                    <p>{{c.name| title}}</p>
                                    <p>({{c.blog_category.all|length}})</p>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </aside>
                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title" style="color: #2d2d2d;">Recent Post</h3>
                        {% for blog in blogs %}
                        <div class="media post_item">
                        <img src="{{ blog.imageUrl }}" alt="post" width="80px" height="80px">
                        <div class="media-body">
                            <a href="{{ blog.absolute_url }}">
                            <h3 style="color: #2d2d2d;">{{blog.title|truncatechars:25}}</h3>
                            </a>
                            <p>{{blog.pub_date_pretty}}</p>
                        </div>
                        </div>
                        {% endfor %}
                    </aside>
                    <aside class="single_sidebar_widget tag_cloud_widget">
                        <h4 class="widget_title" style="color: #2d2d2d;">Tag Clouds</h4>
                        <ul class="list">
                            {% for c in category %}
                            <li>
                                <a href="#">{{c.name| title}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </aside>

                    <aside class="single_sidebar_widget instagram_feeds">
                        <h4 class="widget_title" style="color: #2d2d2d;">Instagram Feeds</h4>
                        <ul class="instagram_row flex-wrap">
                            <li>
                                <a href="#">
                                    <img class="img-fluid" src="{% static 'img/post/post_5.png' %}" alt="">
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img class="img-fluid" src="{% static 'img/post/post_6.png' %}" alt="">
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img class="img-fluid" src="{% static 'img/post/post_7.png' %}" alt="">
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img class="img-fluid" src="{% static 'img/post/post_8.png' %}" alt="">
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img class="img-fluid" src="{% static 'img/post/post_9.png' %}" alt="">
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <img class="img-fluid" src="{% static 'img/post/post_10.png' %}" alt="">
                                </a>
                            </li>
                        </ul>
                    </aside>
                    <aside class="single_sidebar_widget newsletter_widget">
                        <h4 class="widget_title" style="color: #2d2d2d;">Newsletter</h4>
                        <form action="#">
                            <div class="form-group">
                                <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                            type="submit">Subscribe</button>
                        </form>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Area End -->
    
{% endblock %}